# Generated by Django 3.2.9 on 2021-11-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('sku_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('salt_name', models.CharField(max_length=255)),
                ('drug_form', models.CharField(max_length=150)),
                ('pack_size', models.CharField(max_length=150)),
                ('strength', models.CharField(max_length=50)),
                ('product_banned_flag', models.BooleanField(null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('price_per_unit', models.FloatField(null=True)),
            ],
        ),
    ]
